# Generated by Django 4.2.8 on 2024-08-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_id_bp_cok",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
