# Generated by Django 4.2.8 on 2024-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
