# Generated by Django 4.2.8 on 2024-10-17 07:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_title", models.TextField(verbose_name="Название краткое")),
                ("full_title", models.TextField(verbose_name="Название полное")),
                (
                    "logo",
                    models.FileField(upload_to="landing/", verbose_name="Логотип"),
                ),
                ("description", models.TextField(verbose_name="Описание для футера")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "email_support",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email технической поддержки",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "policy",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True,
                        null=True,
                        verbose_name="Политика конфиденциальности",
                    ),
                ),
                (
                    "terms",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Условия использования"
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль организации",
                "verbose_name_plural": "Профили организации",
            },
        ),
    ]
