# Generated by Django 4.2.8 on 2024-10-17 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
