# Generated by Django 4.2.8 on 2024-10-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="is_checked",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Обработана"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
