# Generated by Django 4.2.8 on 2024-10-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "landing",
            "0004_alter_proposal_created_at_alter_proposal_is_checked_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="is_checked",
            field=models.BooleanField(default=False, verbose_name="Обработана"),
        ),
    ]
