# Generated by Django 4.2.8 on 2024-07-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualification",
            name="code",
            field=models.CharField(max_length=15),
        ),
    ]
