# Generated by Django 4.2.8 on 2024-07-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
