# Generated by Django 4.2.8 on 2024-08-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rotation_rotationquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='normative_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
