# Generated by Django 4.2.8 on 2024-07-08 14:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logotype",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="upload/",
                        verbose_name="Логотип организации",
                    ),
                ),
                (
                    "footer_logotype",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="upload/",
                        verbose_name="Логотип для футера (необязательно)",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Краткое название организации",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Направление деятельности организации",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=300,
                        null=True,
                        verbose_name="Полное название организации",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Текст для главной страницы",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=200,
                        null=True,
                        verbose_name="Главный телефон организации",
                    ),
                ),
                (
                    "email",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Адрес электронной почты организации",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Адрес местоположения организации",
                    ),
                ),
                (
                    "req",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Реквизиты организации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль компании",
                "verbose_name_plural": "Профили компаний",
            },
        ),
    ]
