# Generated by Django 4.2.8 on 2024-10-17 07:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="policy",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Политика конфиденциальности"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Условия использования"
            ),
        ),
    ]
