# Generated by Django 4.2.8 on 2024-10-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_profile_policy_profile_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="footer_logotype",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="upload/",
                verbose_name="Логотип маленький",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="logotype",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="upload/",
                verbose_name="Логотип большой (с текстом)",
            ),
        ),
    ]
