# Generated by Django 4.2.8 on 2024-07-12 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.FloatField(default=0.0)),
                ('answer_time', models.DurationField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCheckSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('In Progress', 'В процессе'), ('Completed', 'Завершено')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('progress', models.PositiveIntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('mark', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not started', 'Не пройден'), ('Done', 'Сдан'), ('Failed', 'Не сдан')], default='Not started', max_length=255)),
                ('attempt_count', models.PositiveIntegerField()),
                ('right_answers', models.PositiveIntegerField(default=0)),
                ('time_ticket', models.DurationField(default=datetime.timedelta(0))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.ticket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercourse.usercourse')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorization', models.CharField(choices=[('New', 'Новый'), ('Bad', 'Плохо'), ('Satisfactorily', 'Удовлетворительно'), ('Good', 'Хорошо'), ('Excellent', 'Блистательно')], default='New', max_length=255)),
                ('selected', models.BooleanField()),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('average_answer_time', models.DurationField(default=datetime.timedelta(0))),
                ('force_downgrade_flag', models.BooleanField(default=False)),
                ('consecutive_incorrect_count', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCheckSkillsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_check', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Not Answered', 'Не отвечен'), ('Right', 'Верно'), ('Wrong', 'Не верно')], default='Not Answered', max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question')),
                ('user_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usercourse.useranswer')),
                ('user_check_skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercourse.usercheckskills')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_answer', models.PositiveIntegerField(default=1)),
                ('answer_varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.varient')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercourse.useranswer')),
            ],
        ),
        migrations.CreateModel(
            name='TaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_ticket', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Not Answered', 'Не отвечен'), ('Right', 'Верно'), ('Wrong', 'Не верно')], default='Not Answered', max_length=255)),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercourse.useranswer')),
                ('user_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercourse.userticket')),
            ],
        ),
    ]
