# Generated by Django 4.2.8 on 2024-07-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercourse', '0003_usercourse_selected_usercourse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionticket',
            name='user_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usercourse.useranswer'),
        ),
    ]
