# Generated by Django 4.2.8 on 2024-07-22 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usercourse', '0005_usercheckskills_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
