# Generated by Django 4.2.8 on 2024-07-24 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usercourse', '0007_useranswer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='last_visited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
