# Generated by Django 4.2.8 on 2024-08-04 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercourse', '0009_questionticket_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='course_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
