# Generated by Django 4.2.8 on 2024-08-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercourse', '0010_usercourse_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='prepare',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
