# Generated by Django 4.2.8 on 2024-08-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercourse', '0011_usercourse_prepare_alter_usercourse_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='user_memorization',
            field=models.CharField(blank=True, choices=[('No', 'Нет оценки от пользователя'), ('New', 'Новый'), ('Bad', 'Плохо'), ('Satisfactorily', 'Удовлетворительно'), ('Good', 'Хорошо'), ('Excellent', 'Блистательно')], default='No', max_length=255, null=True),
        ),
    ]
