# Generated by Django 4.2.8 on 2024-08-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercourse', '0013_userdays'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdays',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userdays',
            name='user_course',
        ),
    ]
