# Generated by Django 4.2.8 on 2024-08-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercourse', '0014_alter_userdays_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
